// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  /*
  tutorials: {
    'Home': [
      'intro'
    ],
    'Svelte': [
      {
        type: 'autogenerated',
        dirName: 'svelte',
      },
    ],
    'SvelteKit': [
      {
        type: 'autogenerated',
        dirName: 'sveltekit',
      },
    ]
  }
  */

  tutorials: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ]
  
};

module.exports = sidebars;
